version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      storybook:
        patterns:
          - "@storybook/*"
          - "storybook"
      testing:
        patterns:
          - "@testing-library/*"
          - "jest"
          - "jest-*"
          - "ts-jest"
          - "@types/jest"
          - "@types/jest-axe"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@eslint/*"
          - "typescript-eslint"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
